---
title: "Simulation of Trimmed Mean"
author: "Yixiao Wang" 
vignette: >
  %\VignetteIndexEntry{Simulation of Trimmed Mean}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
description: "This vignette illustrates the simulation process and results for the trimmed mean method."
keywords: ["trimmed mean", "simulation", "robust statistics"]
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = FALSE)
```

## Trimmed Mean Simulation
```{r}
library("fdaPOIFD")
library("magrittr")
library("patchwork")
library("reshape2")
library("ggplot2")
library("tibble")
library(MASS) 
source("../R/plotTrimmedMean.R")
source("../R/SimulateModel.R")
# generate contamination model
SimulateModel <- simulateModel(
  len = 200,
  p = 50,
  q = 0.3,
  M = 10,
  pollution_type = "asymmetric")
data_pofd_con <- intervalPOFD(SimulateModel, observability = 0.5, ninterval = 2, pIncomplete = 1)

plotTrimmedMean(data_pofd_con$pofd,alpha = 0.3, type = "FMD")

```
